
flowchart LR
    sab["Sabrina\n(1954) (Work)"]


    aud["The Audrey Hepburn Collection\n(2008) (Work)"]

    fun["Funny Face\n(1956) (Work)"]


bre["Breakfast at\nTiffanys\n(1961) (Work)"]

aud2["The Audrey Hepburn Collection\n(DVD Manifestation, 2008) (Collection Aggregate)"]

aud3["The Audrey Hepburn Collection\n(DVD Item)"]




sab <-->  aud
aud <-->  fun
bre <--> aud
aud <--> aud2
aud2 <--> aud3